### ISSUE TITLE
Initial Configuration of QTM - Unity - SDK

### ISSUE THREAD

**Issue by ruiabg27** [qualisys/Qualisys-Unity-SDK#6]
Dear All,

Upon connecting to QTM SDK  through Unity using UDP port 22222 an error appears in Unity QTM Streaming window saying:
"Error setting version of protocol"

and when using UDP port 3883 a SocketException occurs:

"SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted."

[Unity Console Error.txt](https://github.com/qualisys/Qualisys-Unity-SDK/files/519441/Unity.Console.Error.txt)

**Comment by qualisys** [comment]
Hi,

You might be using an old version of QTM. Unity plugin is support from QTM 2.11 and upwards but I would recommend using the latest possible version.

Best regards,
Morgan
Qualisys

**Comment by ruiabg27** [comment]
Hi Morgan,

updating the QTM 2.9 isn't an option because the cameras we're using were discontinued in recent versions. Is there a workaround like an older version of QTM-SDK-Unity or a patch we could use for QTM 2.9?

Thanks in advance.

**Comment by qualisys** [comment]
Looking into it... will test here but here is something you can try:
Change the MINOR_VERSION constant to 12 instead of 14 in RTClientSDK.Net/RTProtocol.cs file and run. Version 12 is the one released with QTM 2.9.

Support for Proreflex cameras where dropped in 2.10 so you could update to that version if you want to.
